language: node_js
before_script:
  - npm i -g typescript typings
  - typings install
  - typings install debug
  - npm uninstall jscoverage
#  - tsc
#  - cat gen/match/inputFilterRules.js
  - unset FSD_COVERAGE
  - cat ~/build/jfseb/fdevstart/gulpfile.js
  - gulp default
#  - gulp instrument
node_js:
 - "6"
 - "node"
# - "4"   does not support sourcemaps
# after_script:
#  - npm run instrument
#  - npm run testcov
#  - jscoverage gen/match/inputFilterRules.js gen_cov/xinputFilterRules.js
