language: node_js
before_script:
  - npm i -g typescript typings
  - typings install
  - typings install debug
  - tsc
  - gulp default
  - gulp instrument
node_js:
 - "6"
 - "node"
# - "4"   does not support sourcemaps
after_script:
  - npm run instrument
  - npm run testcov
  - npm run testcov2
  - npm run testcov3
  - npm run testcov4
  - npm run testcov5
  - cat info.lcov
  - type info.lcov
  - ls info.lcov
  - ls -la info.lcov
  - coveralls info.lcov
  - npm run tocoveralls
  - npm run tocoveralls2
  - npm run testcov2
