language: node_js
before_script:
  - npm i -g typescript typings
  - npm i jscoverage
  - npm i jscoverage --save-dev
  - typings install
  - typings install debug
  - tsc
#  - npm ls jscoverage
#  - npm ls tsc
#  - npm ls typescript
#  - npm ls babel
  - gulp default
  - cat gen/match/inputFilterRules.js
#  - gulp instrument
node_js:
 - "6"
 - "node"
# - "4"   does not support sourcemaps
# after_script:
#  - npm run instrument
#  - npm run testcov
#  - jscoverage gen/match/inputFilterRules.js gen_cov/xinputFilterRules.js
