language: node_js
before_script:
  - npm i -g typescript typings
  - typings install
  - typings install debug
  - tsc
  - unset FSD_COVERAGE
  - gulp
#  - gulp instrument
node_js:
 - "6"
 - "node"
# - "4"   does not support sourcemaps
 after_script:
  - jscoverage gen/match/inputFilterRules.js xinputFilterRules.js
  - jscoverage gen/ gen_cov/
  - npm run instrument
  - npm run testcov
